---
- name: oVirt Test
  hosts: 192.168.0.31
  connection: local
  tasks:
    - name: Create VM
      ovirt_vms:
        state: present
        name: TestPC
        cluster: Default
        memory: 1GiB
        cpu_cores: 2
        cpu_sockets: 2
        cpu_shares: 1024
        type: server
        operating_system: windows_2012R2x64
        storage_domain: VM_Storage1
        nics:
          - name: nic1
        auth:
          url: https://192.168.0.31/ovirt-engine/api
          username: admin@internal
          insecure: True
          password: '@R3birth!!'
    - name: Create VM Disk
      ovirt_disk:
        format: cow
        interface: virtio
        name: Test_disk1
        size: 50GiB
        state: present
        storage_domain: VM_Storage1
        vm_name: TestPC
        auth:
          url: https://192.168.0.31/ovirt-engine/api
          username: admin@internal
          insecure: True
          password: '@R3birth!!'
    - name: Edit VM Network
      ovirt_nics:
        name: nic1
        network: ovirtmgmt
        profile: ovirtmgmt
        state: plugged
        vm: TestPC
        auth:
          url: https://192.168.0.31/ovirt-engine/api
          username: admin@internal
          insecure: True
          password: '@R3birth!!'
    - name: Configure Boot Device & ISO
      ovirt_vms:
        name: TestPC
        cd_iso: Windows_2012R2.ISO
        boot_devices:
          - cdrom
          - hd
        state: stopped
        auth:
          url: https://192.168.0.31/ovirt-engine/api
          username: admin@internal
          insecure: True
          password: '@R3birth!!'
    - name: Start VM
      ovirt_vms:
        state: running
        name: TestPC
        auth:
          url: https://192.168.0.31/ovirt-engine/api
          username: admin@internal
          insecure: True
          password: '@R3birth!!'
