---
- name: Zabbix Agent Install
  hosts: localhost
  tasks:
  - name: Install Zabbix RPM
    yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

  - name: Install Zabbix Agent
    yum: name=zabbix-agent state=latest

  - name: Update Zabbix Agent Config File
    copy:
      src: /playbooks/ovirt/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: zabbix
      mode: 0640

  - name: Enable & Start Zabbix Agent
    systemd:
      name: zabbix-agent
      state: started
      enabled: yes

  - name: Open FirewallD Port 10050/TCP
    firewalld:
      port: 10050/tcp
      permanent: true
      state: enabled
      immediate: yes

  - name: Open FirewallD Port 10051/TCP
    firewalld:
      port: 10051/tcp
      permanent: true
      state: enabled
      immediate: yes
    
